### ISSUE TITLE
Cannnot Index string with string "lastreportedAt"

### ISSUE THREAD

**Issue by Sajuwithgithub** [AdmiralSYN-ACKbar/bulkcheck#1]

**Comment by AdmiralSYN-ACKbar** [comment]
Thanks for reporting this. At what point do you see this error? Can you post a screenshot?

**Comment by Sajuwithgithub** [comment]
![Error](https://user-images.githubusercontent.com/51288624/86470533-9e839400-bd09-11ea-82e7-28b6ba2f8f86.JPG)

**Comment by bigalownz** [comment]
i also get these errors too
any help on this ?

**Comment by AdmiralSYN-ACKbar** [comment]
> i also get these errors too
> any help on this ?

Can you send me your inputcsv.txt file? I'd like to confirm that all is well with the setup file. Thanks.

**Comment by bigalownz** [comment]
i read how to set it up on

https://www.admiralsyn-ackbar.com/abuseip-bulk-check-script/

I got it working in the end
in the input.csv the format was "192.168.1.0"
but i removed the "" and just have 192.168.1.0 and it worked ok

also i tried it with just a plan txt file with out the "" and it worked ok to

**Comment by Bribber** [comment]
Hello! I am running into the same issue as Sajuwithgithub, but am running into `jq: error (at <stdin>:0): Cannot index array with string "lastReportedAt"`. I have formatted the input file in the same manner as the previous attempts and it is only with a recent list of IPs that it started hitting me with this error. To see if it was the file, I went back and ran a previous list that I had success with only to be greeted with the same error. None of the files contain quotations and trying them as plain txt files did not work. Seems to be mainly having an issue with the array on line 314, as it will check the IPs against AbuseIPDB but will not output them to the target csv.

**Comment by AdmiralSYN-ACKbar** [comment]
> Hello! I am running into the same issue as Sajuwithgithub, but am running into `jq: error (at <stdin>:0): Cannot index array with string "lastReportedAt"`. I have formatted the input file in the same manner as the previous attempts and it is only with a recent list of IPs that it started hitting me with this error. To see if it was the file, I went back and ran a previous list that I had success with only to be greeted with the same error. None of the files contain quotations and trying them as plain txt files did not work. Seems to be mainly having an issue with the array on line 314, as it will check the IPs against AbuseIPDB but will not output them to the target csv.

Hi Bribber, can you send me your input.txt and IP CSV list? I can be reached at admiral@admiralsyn-ackbar.com. Thanks!
