### ISSUE TITLE
Authentication error 

### ISSUE THREAD

**Issue by faheemarshad** [AdmiralSYN-ACKbar/bulkcheck#4]
Hi, I ran a PowerShell script to check bulk IP addresses from a .csv file format, It runs but does not generate an output file in the folder. I created a new key on abuseDB after creating an account. I am seeing an authentication failure on the PS console. 

access denied (authentication_failed)
Your credential could not be authenticated: "credentials are missing." you will not be permitted access until your credentials are verified

I'm just wondering, apart from "Key": do I need to specify any username/password inside a script? or is there something else I am missing

**Comment by AdmiralSYN-ACKbar** [comment]
You do not need to enter a username/password inside the script. Can you post a screenshot of your input as well as the Powershell console output?
