### ISSUE TITLE
# Reports returned is incorrect

### ISSUE THREAD

**Issue by sdaughtry1** [AdmiralSYN-ACKbar/bulkcheck#5]
A comparison of 3 IP addresses showed a vast discrepancy between what the Powershell script returns for the # of malicious reports versus manually checking the same IP address via the AbuseIPDB.com web site. Check 36.112.171.51 (script = 7507 / manual = 51513), 79.124.62.82 (4653 versus 94465) and 36.110.228.254 (4696 versus 104809). I redownloaded/rechecked the tallies with the current .PS1 file on Github and the conclusion was the same - the script is returning incorrect values.

**Comment by ghost** [comment]
This might be because the script does not set the "maxAgeInDays" parameter when querying the API. So the API uses the default "maxAgeInDays" value of 30 days, see https://docs.abuseipdb.com/#check-endpoint

This could be the reason the script always returns less reports, because it only counts reports made in the last 30 days.

**Comment by AdmiralSYN-ACKbar** [comment]
Thanks for jumping in here @bastiaan-deltics. Yes, the discrepancy between MaxAgeInDays (which by default is 30 for API calls) and lookups through a web browser at abuseipdb.com (which go further back) are likely why this is happening. An adjustable MaxAgeInDays value is something that I would like to implement in a future version of the script.

**Comment by sdaughtry1** [comment]
I modified line 317 to this:
Invoke-WebRequest -Uri ("https://api.abuseipdb.com/api/v2/check?ipAddress=$($_.IP)&maxAgeInDays=365") -Headers @{'Accept' = 'application/json'; 'Key' = $ApiKey} -usebasicparsing | add-content -path $jsonTempPath

The max # of days the API can return is 365 (unlike the AbuseIPDB web site, where a single IP query goes back to day #1).. its the best that I could do. I recommend modifying the script's readme file to inform users that it returns only the past 30 days though...
